//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Powered_Cleaner.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Powered_Cleaner.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ABOUT.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ADVANCED.
        /// </summary>
        internal static string advanced {
            get {
                return ResourceManager.GetString("advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analysis Completed.
        /// </summary>
        internal static string analysisCompleted {
            get {
                return ResourceManager.GetString("analysisCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analyze.
        /// </summary>
        internal static string analyze {
            get {
                return ResourceManager.GetString("analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à APPLICATIONS.
        /// </summary>
        internal static string applications {
            get {
                return ResourceManager.GetString("applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Audio Device :.
        /// </summary>
        internal static string audioDevice {
            get {
                return ResourceManager.GetString("audioDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BIOS Version :.
        /// </summary>
        internal static string biosVersion {
            get {
                return ResourceManager.GetString("biosVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check for updates.
        /// </summary>
        internal static string checkForUpdates {
            get {
                return ResourceManager.GetString("checkForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à System.
        /// </summary>
        internal static string chkSystem {
            get {
                return ResourceManager.GetString("chkSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Windows Explorer.
        /// </summary>
        internal static string chkWinExplorer {
            get {
                return ResourceManager.GetString("chkWinExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run Cleaner.
        /// </summary>
        internal static string clean {
            get {
                return ResourceManager.GetString("clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cleaning Completed.
        /// </summary>
        internal static string cleaningCompleted {
            get {
                return ResourceManager.GetString("cleaningCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clean Recycle bin.
        /// </summary>
        internal static string cleanRecycleBin {
            get {
                return ResourceManager.GetString("cleanRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clipboard.
        /// </summary>
        internal static string clipboard {
            get {
                return ResourceManager.GetString("clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close program after cleaning.
        /// </summary>
        internal static string ClosePcClean {
            get {
                return ResourceManager.GetString("ClosePcClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DASHBOARD.
        /// </summary>
        internal static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Only delete files in Windows Temp folders older than 24 hours.
        /// </summary>
        internal static string DelOnlyWinTemp24 {
            get {
                return ResourceManager.GetString("DelOnlyWinTemp24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Downloaded Installations.
        /// </summary>
        internal static string downloadedInstall {
            get {
                return ResourceManager.GetString("downloadedInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download History.
        /// </summary>
        internal static string downloadHistory {
            get {
                return ResourceManager.GetString("downloadHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hard Drive Disk :.
        /// </summary>
        internal static string hdd {
            get {
                return ResourceManager.GetString("hdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à History.
        /// </summary>
        internal static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Internet Cache.
        /// </summary>
        internal static string internetCache {
            get {
                return ResourceManager.GetString("internetCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manufacturer :.
        /// </summary>
        internal static string manufacturer {
            get {
                return ResourceManager.GetString("manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Congratulations, You have the latest version !.
        /// </summary>
        internal static string mBoxLatestVersion {
            get {
                return ResourceManager.GetString("mBoxLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à needs to be closed to clean the Internet Cache..
        /// </summary>
        internal static string mBoxProcessBefore {
            get {
                return ResourceManager.GetString("mBoxProcessBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want Powered Cleaner to close.
        /// </summary>
        internal static string mBoxProcessQuestion {
            get {
                return ResourceManager.GetString("mBoxProcessQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A new update is ready to download !.
        /// </summary>
        internal static string mBoxUpdateReadyBefore {
            get {
                return ResourceManager.GetString("mBoxUpdateReadyBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to get the new version now ?.
        /// </summary>
        internal static string mBoxUpdateReadyQuestion {
            get {
                return ResourceManager.GetString("mBoxUpdateReadyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verify your internet connexion.
        /// </summary>
        internal static string mBoxVerifyConn {
            get {
                return ResourceManager.GetString("mBoxVerifyConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Before run analysis, please make sure there is no updates in progress.
        /// </summary>
        internal static string mBoxWUpdateBefore {
            get {
                return ResourceManager.GetString("mBoxWUpdateBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to check now ?.
        /// </summary>
        internal static string mBoxWUpdateQuestion {
            get {
                return ResourceManager.GetString("mBoxWUpdateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MB to be removed. (Approximative size).
        /// </summary>
        internal static string mbToRemove {
            get {
                return ResourceManager.GetString("mbToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Memory (RAM) :.
        /// </summary>
        internal static string memory {
            get {
                return ResourceManager.GetString("memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Memory Dumps.
        /// </summary>
        internal static string memoryDumps {
            get {
                return ResourceManager.GetString("memoryDumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minimize to System Tray.
        /// </summary>
        internal static string minSysTray {
            get {
                return ResourceManager.GetString("minSysTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Model : .
        /// </summary>
        internal static string model {
            get {
                return ResourceManager.GetString("model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Containing Folder.
        /// </summary>
        internal static string openContainingFolder {
            get {
                return ResourceManager.GetString("openContainingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Powered Cleaner....
        /// </summary>
        internal static string openPc {
            get {
                return ResourceManager.GetString("openPc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OPTIONS.
        /// </summary>
        internal static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Processor :.
        /// </summary>
        internal static string processor {
            get {
                return ResourceManager.GetString("processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit.
        /// </summary>
        internal static string quit {
            get {
                return ResourceManager.GetString("quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recent Documents.
        /// </summary>
        internal static string recentDocs {
            get {
                return ResourceManager.GetString("recentDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run Powered Cleaner when the computer starts.
        /// </summary>
        internal static string runPcStart {
            get {
                return ResourceManager.GetString("runPcStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MB cleaned. (Approximative size).
        /// </summary>
        internal static string sizeCleaned {
            get {
                return ResourceManager.GetString("sizeCleaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à STORAGE.
        /// </summary>
        internal static string storage {
            get {
                return ResourceManager.GetString("storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SYSTEM.
        /// </summary>
        internal static string system {
            get {
                return ResourceManager.GetString("system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à System Information.
        /// </summary>
        internal static string systemInfo {
            get {
                return ResourceManager.GetString("systemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à System Name :.
        /// </summary>
        internal static string systemName {
            get {
                return ResourceManager.GetString("systemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à System Type : .
        /// </summary>
        internal static string systemType {
            get {
                return ResourceManager.GetString("systemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temporary Files.
        /// </summary>
        internal static string temporaryFiles {
            get {
                return ResourceManager.GetString("temporaryFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thumbnail Cache.
        /// </summary>
        internal static string thumbnailCache {
            get {
                return ResourceManager.GetString("thumbnailCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Video Controller :.
        /// </summary>
        internal static string videoController {
            get {
                return ResourceManager.GetString("videoController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View all files.
        /// </summary>
        internal static string viewAllFiles {
            get {
                return ResourceManager.GetString("viewAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WEB BROWSER.
        /// </summary>
        internal static string webBrowser {
            get {
                return ResourceManager.GetString("webBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Windows Error Reporting.
        /// </summary>
        internal static string winErrorReporting {
            get {
                return ResourceManager.GetString("winErrorReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WINDOWS EXPLORER.
        /// </summary>
        internal static string winExplorer {
            get {
                return ResourceManager.GetString("winExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Windows Logs.
        /// </summary>
        internal static string winLogFiles {
            get {
                return ResourceManager.GetString("winLogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Windows Update.
        /// </summary>
        internal static string winUpdate {
            get {
                return ResourceManager.GetString("winUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Windows Version :.
        /// </summary>
        internal static string winVersion {
            get {
                return ResourceManager.GetString("winVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Updates History.
        /// </summary>
        internal static string WUpdateHist {
            get {
                return ResourceManager.GetString("WUpdateHist", resourceCulture);
            }
        }
    }
}
